[paths]
data = mydata

[listens]
http = :5556
tcp = :5555
; 35.221.150.154:5556
[buffer]
; File handle LRU capacity (optional, default: 700)
; file_handle_lru_capacity = 700

[auth]
no_auth_user = root
root_token = bc4718ff040e789b76fc7bbeebb0f7a5
